export const GET_DEPLOYMENTS_START = 'GET_DEPLOYMENTS_START';
export const GET_DEPLOYMENTS_SUCCESS = 'GET_DEPLOYMENTS_SUCCESS';
export const GET_DEPLOYMENTS_FAIL = 'GET_DEPLOYMENTS_FAIL';

export const CREATE_DEPLOYMENT_START = 'ADD_DEPLOYMENT_START';
export const CREATE_DEPLOYMENT_SUCCESS = 'ADD_DEPLOYMENT_SUCCESS';
export const CREATE_DEPLOYMENT_FAIL = 'ADD_DEPLOYMENT_FAIL';

export const REMOVE_DEPLOYMENT_START = 'REMOVE_DEPLOYMENT_START';
export const REMOVE_DEPLOYMENT_SUCCESS = 'REMOVE_DEPLOYMENT_SUCCESS';
export const REMOVE_DEPLOYMENT_FAIL = 'REMOVE_DEPLOYMENT_FAIL';

export const DECREMENT_DEPLOYMENT_COUNTDOWN = 'DECREMENT_DEPLOYMENT_SECONDS_TO_SHOW';

export const GET_TEMPLATES_START = 'GET_TEMPLATES_START';
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const GET_TEMPLATES_FAIL = 'GET_TEMPLATES_FAIL';